### ISSUE TITLE
Skip when no changes to source code files?

### ISSUE THREAD

**Issue by IndrajeetPatil** [lorenzwalthert/touchstone#117]
Given how expensive this workflow is, do you think `{touchstone}` should skip benchmarking when there is no change to any files containing source code?

E.g., [here](https://github.com/r-lib/styler/pull/1012) only a YAML file was changed, but we are still benchmarking ever commit in this PR, which is unnecessary since this file doesn't contain any source code and any change to it will have no effect on performance.

**Comment by lorenzwalthert** [comment]
Maybe source files are too restrictive. But we could restrict it to source files + `DESCRIPTION` + `touchstone/*`? I.e. if dependencies change, we don't want to skip.

**Comment by IndrajeetPatil** [comment]
Yes, that sounds good to me!

Thanks for being open to the idea.

**Comment by assignUser** [comment]
You can easily implement  this change directly in your workflow file by adding the [`paths` node:](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-paths)
```yml
on: 
  pull_request:
    paths:
      # Filter by dir
     - "r/**"
     - "src/**"
     - "touchstone/**"
     # or file type
     - "*.r"
     # or specific files
     - ".github/workflows/touchstone-*.yaml"
     - DESCRIPTION
```
I think running without filter should be the default but we should probably add some documentation about this functionality :+1:
