### ISSUE TITLE
Use newer R package caching action in GitHub Action scripts

### ISSUE THREAD

**Issue by lorenzwalthert** [lorenzwalthert/touchstone#50]
https://github.com/r-lib/actions/tree/master/setup-r-dependencies. Move {ggplot2} and {dplyr} from manual install to `extra-dependencies`.

```yaml
steps:
- uses: actions/checkout@master
- uses: r-lib/actions/setup-r@v1
- uses: r-lib/actions/setup-r-dependencies@v1
  with:
    cache-version: 2
    extra-packages: |
      ggplot2
      rcmdcheck
      dplyr
#    needs: | # not sure what this is?
#      website
 #     coverage
```
